<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>TheSpellBrigadeHelper</AssemblyName>
    <Product>The Spell Brigade helper</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>TheSpellBrigadeHelper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="HarmonyX" Version="2.10.2" />
  </ItemGroup>

  <!-- 游戏 DLL 引用 - 使用通配符引用整个 interop 目录 -->
  <ItemGroup>
    <!-- 将以下目录替换为你的游戏目录 -->
    <Reference Include="E:\SteamLibrary\steamapps\common\The Spell Brigade\BepInEx\interop\*.dll" />
  </ItemGroup>
</Project>
